export interface CatalogProduct {
  id: number
  name: string
  category: string
  price: number
  priceDisplay: string
  mileage: string
  condition: string
  warranty: string
  rating: number
  reviews: number
  image: string
  description: string
  fits: string
  sku: string
  inStock: boolean
}

export const PRODUCTS_CATALOG: CatalogProduct[] = [
  // Engines
  {
    id: 1,
    name: '2018 Acura MDX Complete Engine',
    category: 'Engines',
    price: 1299,
    priceDisplay: '$1,299',
    mileage: '82,000 miles',
    condition: 'Excellent',
    warranty: '90 days',
    rating: 4.8,
    reviews: 24,
    image: '/images/product-engine-1.png',
    description: 'Complete 3.5L V6 engine assembly from a 2018 Acura MDX. Fully tested, compression verified, and ready to install. Includes intake manifold, exhaust manifolds, and all accessories.',
    fits: '2016-2020 Acura MDX',
    sku: 'ENG-MDX-2018-001',
    inStock: true,
  },
  {
    id: 2,
    name: 'Automatic Transmission Assembly',
    category: 'Transmissions',
    price: 899,
    priceDisplay: '$899',
    mileage: '91,000 miles',
    condition: 'Good',
    warranty: '90 days',
    rating: 4.9,
    reviews: 18,
    image: '/images/product-transmission-1.png',
    description: 'Complete automatic transmission assembly, pressure tested and shift verified. Includes torque converter. Fluid drained and inspected for metal shavings — clean report.',
    fits: 'Multiple makes and models — verify with VIN',
    sku: 'TRN-AUTO-002',
    inStock: true,
  },
  {
    id: 3,
    name: 'High-Quality Alternator',
    category: 'Electrical',
    price: 249,
    priceDisplay: '$249',
    mileage: '75,000 miles',
    condition: 'Excellent',
    warranty: '90 days',
    rating: 4.7,
    reviews: 31,
    image: '/images/product-alternator-1.png',
    description: 'OEM alternator tested for output voltage and amperage under load. Bearings inspected, pulley in excellent condition. Guaranteed charging performance.',
    fits: 'Multiple makes and models — verify with VIN',
    sku: 'ELC-ALT-003',
    inStock: true,
  },
  {
    id: 4,
    name: 'Complete Radiator Assembly',
    category: 'Cooling',
    price: 399,
    priceDisplay: '$399',
    mileage: '85,000 miles',
    condition: 'Excellent',
    warranty: '90 days',
    rating: 5.0,
    reviews: 12,
    image: '/images/product-radiator-1.png',
    description: 'Complete radiator assembly with fans and shroud. Pressure tested for leaks, fins straight and clean. Includes upper and lower hose connections.',
    fits: 'Multiple makes and models — verify with VIN',
    sku: 'COL-RAD-004',
    inStock: true,
  },
  // Additional Engines
  {
    id: 5,
    name: '2015 Honda Accord 2.4L Engine',
    category: 'Engines',
    price: 1099,
    priceDisplay: '$1,099',
    mileage: '68,000 miles',
    condition: 'Excellent',
    warranty: '90 days',
    rating: 4.9,
    reviews: 41,
    image: '/images/acura/engines/acura-ilx-engine.png',
    description: 'K24W 2.4L 4-cylinder engine, compression tested across all cylinders. Timing chain inspected, no oil consumption issues. Complete with accessories.',
    fits: '2013-2017 Honda Accord, Acura ILX',
    sku: 'ENG-ACC-2015-005',
    inStock: true,
  },
  {
    id: 6,
    name: '3.2L V6 Engine — Acura CL/TL',
    category: 'Engines',
    price: 949,
    priceDisplay: '$949',
    mileage: '95,000 miles',
    condition: 'Good',
    warranty: '90 days',
    rating: 4.6,
    reviews: 15,
    image: '/images/acura/engines/acura-cl-engine-v6-3.2l.png',
    description: 'J32A 3.2L V6 engine from Acura CL. Leak-down tested, healthy oil pressure readings. Ideal replacement for CL and TL applications.',
    fits: '1999-2003 Acura CL, TL',
    sku: 'ENG-CL-32L-006',
    inStock: true,
  },
  {
    id: 7,
    name: 'RDX 2.3L Turbo Engine',
    category: 'Engines',
    price: 1449,
    priceDisplay: '$1,449',
    mileage: '71,000 miles',
    condition: 'Excellent',
    warranty: '90 days',
    rating: 4.8,
    reviews: 9,
    image: '/images/acura/engines/acura-rdx-engine.png',
    description: 'K23A1 2.3L turbocharged engine from Acura RDX. Turbo inspected for shaft play — none found. Boost tested and ready to ship.',
    fits: '2007-2012 Acura RDX',
    sku: 'ENG-RDX-23T-007',
    inStock: true,
  },
  // Transmissions
  {
    id: 8,
    name: 'Manual Transmission — 6-Speed',
    category: 'Transmissions',
    price: 749,
    priceDisplay: '$749',
    mileage: '78,000 miles',
    condition: 'Excellent',
    warranty: '90 days',
    rating: 4.7,
    reviews: 22,
    image: '/images/acura/transmissions/acura-cl-transmission-manual.png',
    description: '6-speed manual transmission, all gears verified for smooth engagement. Synchros in excellent condition, no grinding. Includes shift linkage.',
    fits: 'Multiple makes and models — verify with VIN',
    sku: 'TRN-MAN6-008',
    inStock: true,
  },
  {
    id: 9,
    name: 'CVT Transmission Assembly',
    category: 'Transmissions',
    price: 1199,
    priceDisplay: '$1,199',
    mileage: '54,000 miles',
    condition: 'Excellent',
    warranty: '90 days',
    rating: 4.5,
    reviews: 14,
    image: '/images/acura/transmissions/acura-cl-transmission-automatic.png',
    description: 'Continuously variable transmission, low mileage unit. Belt and pulleys inspected, fluid analyzed. Smooth operation verified on test bench.',
    fits: 'Honda / Acura CVT applications — verify with VIN',
    sku: 'TRN-CVT-009',
    inStock: true,
  },
  // Drivetrain
  {
    id: 10,
    name: 'CV Axle Shaft Assembly',
    category: 'Drivetrain',
    price: 129,
    priceDisplay: '$129',
    mileage: '62,000 miles',
    condition: 'Excellent',
    warranty: '90 days',
    rating: 4.8,
    reviews: 37,
    image: '/images/product-drivetrain-1.png',
    description: 'Complete CV axle shaft with boots intact — no cracks or grease leaks. Joints tested for play, smooth rotation confirmed.',
    fits: 'Multiple makes and models — verify with VIN',
    sku: 'DRV-CVA-010',
    inStock: true,
  },
  {
    id: 11,
    name: 'Rear Differential Assembly',
    category: 'Drivetrain',
    price: 549,
    priceDisplay: '$549',
    mileage: '88,000 miles',
    condition: 'Good',
    warranty: '90 days',
    rating: 4.6,
    reviews: 11,
    image: '/images/category-drivetrain.png',
    description: 'Rear differential assembly, gears inspected for wear pattern. Fluid drained and checked — no metal contamination. Quiet operation verified.',
    fits: 'AWD / RWD applications — verify with VIN',
    sku: 'DRV-DIF-011',
    inStock: true,
  },
  // Electrical
  {
    id: 12,
    name: 'Starter Motor',
    category: 'Electrical',
    price: 149,
    priceDisplay: '$149',
    mileage: '70,000 miles',
    condition: 'Excellent',
    warranty: '90 days',
    rating: 4.7,
    reviews: 28,
    image: '/images/category-electrical.png',
    description: 'OEM starter motor, bench tested for engagement and cranking speed. Solenoid verified, brushes in excellent condition.',
    fits: 'Multiple makes and models — verify with VIN',
    sku: 'ELC-STR-012',
    inStock: true,
  },
  {
    id: 13,
    name: 'Engine Control Module (ECM)',
    category: 'Electrical',
    price: 299,
    priceDisplay: '$299',
    mileage: 'N/A',
    condition: 'Excellent',
    warranty: '90 days',
    rating: 4.5,
    reviews: 16,
    image: '/images/category-electrical.png',
    description: 'Engine control module pulled from running vehicle. All communication protocols verified. Programming service available — provide your VIN.',
    fits: 'VIN-specific — contact us to verify compatibility',
    sku: 'ELC-ECM-013',
    inStock: true,
  },
  // Cooling
  {
    id: 14,
    name: 'A/C Compressor',
    category: 'Cooling',
    price: 229,
    priceDisplay: '$229',
    mileage: '79,000 miles',
    condition: 'Good',
    warranty: '90 days',
    rating: 4.6,
    reviews: 19,
    image: '/images/category-cooling.png',
    description: 'A/C compressor with clutch, tested for engagement and pressure output. No bearing noise, clean refrigerant history.',
    fits: 'Multiple makes and models — verify with VIN',
    sku: 'COL-ACC-014',
    inStock: true,
  },
  {
    id: 15,
    name: 'Water Pump Assembly',
    category: 'Cooling',
    price: 89,
    priceDisplay: '$89',
    mileage: '66,000 miles',
    condition: 'Excellent',
    warranty: '90 days',
    rating: 4.8,
    reviews: 23,
    image: '/images/category-cooling.png',
    description: 'Water pump with no bearing play or weep hole leakage. Impeller inspected — all vanes intact. Gasket surface clean.',
    fits: 'Multiple makes and models — verify with VIN',
    sku: 'COL-WTP-015',
    inStock: true,
  },
  // Brakes
  {
    id: 16,
    name: 'Brake Caliper & Rotor Set',
    category: 'Brakes',
    price: 179,
    priceDisplay: '$179',
    mileage: '58,000 miles',
    condition: 'Excellent',
    warranty: '90 days',
    rating: 4.7,
    reviews: 26,
    image: '/images/product-brakes-1.png',
    description: 'Front brake caliper and rotor set. Caliper pistons move freely, no seized slides. Rotor measured above minimum thickness spec.',
    fits: 'Multiple makes and models — verify with VIN',
    sku: 'BRK-CRS-016',
    inStock: true,
  },
  {
    id: 17,
    name: 'ABS Pump & Module',
    category: 'Brakes',
    price: 349,
    priceDisplay: '$349',
    mileage: '81,000 miles',
    condition: 'Good',
    warranty: '90 days',
    rating: 4.5,
    reviews: 13,
    image: '/images/category-brakes.png',
    description: 'ABS hydraulic pump and control module, tested for fault codes — none present. Connectors clean, no corrosion.',
    fits: 'VIN-specific — contact us to verify compatibility',
    sku: 'BRK-ABS-017',
    inStock: true,
  },
  // Suspension
  {
    id: 18,
    name: 'Strut & Coil Spring Assembly',
    category: 'Suspension',
    price: 139,
    priceDisplay: '$139',
    mileage: '64,000 miles',
    condition: 'Excellent',
    warranty: '90 days',
    rating: 4.8,
    reviews: 33,
    image: '/images/product-suspension-1.png',
    description: 'Complete strut assembly with coil spring and mount. No leaks, full damping verified. Spring free of cracks and corrosion.',
    fits: 'Multiple makes and models — verify with VIN',
    sku: 'SUS-STR-018',
    inStock: true,
  },
  {
    id: 19,
    name: 'Power Steering Rack & Pinion',
    category: 'Suspension',
    price: 289,
    priceDisplay: '$289',
    mileage: '77,000 miles',
    condition: 'Good',
    warranty: '90 days',
    rating: 4.6,
    reviews: 17,
    image: '/images/category-suspension.png',
    description: 'Power steering rack and pinion assembly. Pressure tested — no internal or external leaks. Tie rod ends included, boots intact.',
    fits: 'Multiple makes and models — verify with VIN',
    sku: 'SUS-RCK-019',
    inStock: true,
  },
  // Body
  {
    id: 20,
    name: 'Front Door Assembly — Complete',
    category: 'Body',
    price: 329,
    priceDisplay: '$329',
    mileage: 'N/A',
    condition: 'Excellent',
    warranty: '90 days',
    rating: 4.7,
    reviews: 8,
    image: '/images/product-body-1.png',
    description: 'Complete front door assembly with glass, regulator, latch, and wiring harness. No dents, rust, or paint damage. Color code available on request.',
    fits: 'VIN-specific — contact us to verify color and fit',
    sku: 'BDY-DOR-020',
    inStock: true,
  },
  {
    id: 21,
    name: 'Headlight Assembly — OEM',
    category: 'Body',
    price: 159,
    priceDisplay: '$159',
    mileage: 'N/A',
    condition: 'Excellent',
    warranty: '90 days',
    rating: 4.8,
    reviews: 21,
    image: '/images/product-body-1.png',
    description: 'OEM headlight assembly with clear lens — no fogging, cracks, or moisture. All tabs intact, adjusters functional.',
    fits: 'Multiple makes and models — verify with VIN',
    sku: 'BDY-HDL-021',
    inStock: true,
  },
  // Exhaust
  {
    id: 22,
    name: 'Catalytic Converter — OEM',
    category: 'Exhaust',
    price: 449,
    priceDisplay: '$449',
    mileage: '72,000 miles',
    condition: 'Excellent',
    warranty: '90 days',
    rating: 4.6,
    reviews: 10,
    image: '/images/product-exhaust-1.png',
    description: 'OEM catalytic converter, substrate intact and efficient. No rattle, honeycomb inspected via borescope. Legal for street use — verify your state regulations.',
    fits: 'Multiple makes and models — verify with VIN',
    sku: 'EXH-CAT-022',
    inStock: true,
  },
  {
    id: 23,
    name: 'Exhaust Manifold',
    category: 'Exhaust',
    price: 119,
    priceDisplay: '$119',
    mileage: '84,000 miles',
    condition: 'Good',
    warranty: '90 days',
    rating: 4.5,
    reviews: 12,
    image: '/images/product-exhaust-1.png',
    description: 'Cast iron exhaust manifold — no cracks or warpage. Flange surfaces machined flat, all studs removed cleanly.',
    fits: 'Multiple makes and models — verify with VIN',
    sku: 'EXH-MAN-023',
    inStock: true,
  },
  {
    id: 24,
    name: 'Muffler & Tailpipe Assembly',
    category: 'Exhaust',
    price: 99,
    priceDisplay: '$99',
    mileage: '61,000 miles',
    condition: 'Excellent',
    warranty: '90 days',
    rating: 4.7,
    reviews: 15,
    image: '/images/product-exhaust-1.png',
    description: 'OEM muffler and tailpipe, minimal surface rust, no perforation. Quiet operation with factory sound level.',
    fits: 'Multiple makes and models — verify with VIN',
    sku: 'EXH-MUF-024',
    inStock: true,
  },
]

export function getProductById(id: number): CatalogProduct | undefined {
  return PRODUCTS_CATALOG.find((p) => p.id === id)
}

export function getRelatedProducts(product: CatalogProduct, limit = 4): CatalogProduct[] {
  const sameCategory = PRODUCTS_CATALOG.filter(
    (p) => p.category === product.category && p.id !== product.id
  )
  const others = PRODUCTS_CATALOG.filter(
    (p) => p.category !== product.category && p.id !== product.id
  )
  return [...sameCategory, ...others].slice(0, limit)
}
